name: ci

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: "2.0.6"
            - name: Run fmt
              run: |
                  deno fmt --check --indent-width=4
            - name: Run lint
              run: |
                  deno lint
            - name: Run type-check
              run: |
                  deno check ./ast/*
                  deno check ./lexer/*
                  deno check ./parser/*
                  deno check ./repl/*
                  deno check ./token/*
            - name: Run tests
              run: |
                  deno test -A
